openapi: 3.0.0
info:
  title: Validus REST API
  version: "1.0.0"
paths:
  /hello:
    get:
      summary: Hello World endpoint
      operationId: hello
      responses:
        "200":
          description: Returns a welcome message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloResponse"
components:
  schemas:
    HelloResponse:
      type: object
      properties:
        message:
          type: string
