# Global configuration
debug = true

# Feature flags
[features]
dev_mode = true
rest_api = true
grpc_api = false
fix_api  = false

[rest]
bind_on = "127.0.0.1:8080"

# Logging configuration
[logging]
output = "./logs/app.log"
level  = "info"
format = "json"

# Engine configuration
[engine]
machine_id = 100
